export const SAVED_VENUES = [
  {
    id: 'venue_1',
    venueName: "St. Xavier's Engineering College",
    region: "North",
    state: "Delhi",
    city: "New Delhi",
    address: "Plot No. 12, Sector 10, Dwarka, New Delhi",
    pinCode: "110075",
    isMapAccurate: "yes",
    ownerName: "Rev. Fr. John D'Souza",
    ownerContact: "9876543210",
    ownerEmail: "director@stxaviers.edu",
    adminName: "Dr. Sandeep Kumar",
    adminContact: "9812345678",
    itAdminName: "Rakesh Sharma",
    itAdminContact: "9988776655",
    venueEmail: "info@stxaviers.edu",
    landline: "011-25087654",
    alternateContact: "9876543211",
    // Optional accessibility defaults
    distCityCentre: "15 km",
    distAirport: "12 km",
    distRailway: "18 km",
    distBusStop: "400 meters",
    busStopName: "Sector 10 Dwarka Metro",
    distPoliceStation: "1.5 km",
    policeStationName: "Dwarka Sector 23 Station",
    distHospital: "2 km",
    hospitalName: "Venkateshwar Hospital",
    distFireStation: "3.5 km",
    approachRoadQuality: "Good",
    convenienceFeedback: "Well-connected by Metro and wide roads."
  },
  {
    id: 'venue_2',
    venueName: "Global Institute of Technology",
    region: "West",
    state: "Maharashtra",
    city: "Mumbai",
    address: "GIT Campus, K.P. Road, Powai, Mumbai",
    pinCode: "400076",
    isMapAccurate: "yes",
    ownerName: "Dr. Vinayak G. Patel",
    ownerContact: "9820012345",
    ownerEmail: "trustee@git.edu",
    adminName: "Prof. Milind Deshmukh",
    adminContact: "9892233445",
    itAdminName: "Anil Kadam",
    itAdminContact: "9167788990",
    venueEmail: "contact@git.edu",
    landline: "022-25761234",
    alternateContact: "9820012346",
    distCityCentre: "20 km",
    distAirport: "10 km",
    distRailway: "5 km",
    distBusStop: "200 meters",
    busStopName: "Powai Lake Bus Stop",
    distPoliceStation: "1.2 km",
    policeStationName: "Powai Police Station",
    distHospital: "1.5 km",
    hospitalName: "Hiranandani Hospital",
    distFireStation: "2.8 km",
    approachRoadQuality: "Good",
    convenienceFeedback: "Located in a prime area, easily accessible via public buses."
  },
  {
    id: 'venue_3',
    venueName: "R.V. College of Technology",
    region: "South",
    state: "Karnataka",
    city: "Bangalore",
    address: "RV Vidyaniketan, Mysore Road, Bangalore",
    pinCode: "560059",
    isMapAccurate: "yes",
    ownerName: "Sri. A. V. S. Murthy",
    ownerContact: "9448011223",
    ownerEmail: "secretary@rvcet.edu.in",
    adminName: "Dr. K. N. Subramanya",
    adminContact: "9449822334",
    itAdminName: "Srinivas Rao",
    itAdminContact: "9845055667",
    venueEmail: "principal@rvce.edu.in",
    landline: "080-67178000",
    alternateContact: "9448011224",
    distCityCentre: "12 km",
    distAirport: "45 km",
    distRailway: "1.5 km",
    distBusStop: "100 meters",
    busStopName: "RV College Bus Stop",
    distPoliceStation: "800 meters",
    policeStationName: "Kengeri Police Station",
    distHospital: "1.2 km",
    hospitalName: "BGS Gleneagles Global Hospital",
    distFireStation: "3 km",
    approachRoadQuality: "Good",
    convenienceFeedback: "Direct bus connectivity and near to Kengeri Metro/Railway stations."
  }
];
